sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.8
before_install:  
  - sudo apt-get update -yq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -yq docker-engine
script:
  - make torpedo
  - DOCKER_HUB_REPO=adityadani DOCKER_HUB_TORPEDO_IMAGE=torpedo DOCKER_HUB_TAG=latest make container
notifications:
  email:
    recipients:
      - aditya@portworx.com
      - gou@portworx.com
      - jv@portworx.com
    on_success: always
    on_failure: always
