##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nginx-sc
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  shared: "true"
allowVolumeExpansion: true