apiVersion: v1
kind: Secret
metadata:
  name: volume-secrets
type: Opaque
data:
  mysql-secret: WW91IHNuZWFreSBsaXR0bGUgcGlnbGV0IQ==
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data
spec:
  storageClassName: mysql-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi