kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sysbench-sc
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  priority_io: "high"
  io_profile: "db"
allowVolumeExpansion: true