kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-sysbench-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  priority_io: "high"
  io_profile: "db"
allowVolumeExpansion: true
---
# Azure sysbench storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-mysql-sysbench-sc
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: pwxautomation
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sysbench-mysql-data
  annotations:
    azure-storage-class: azure-mysql-sysbench-sc
spec:
  storageClassName: mysql-sysbench-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi