apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysbench
  labels:
    app: sysbench
spec:
  selector:
    matchLabels:
      app: sysbench
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: sysbench
    spec:
      schedulerName: stork
      containers:
        - image: mysql:5.7
          name: mysql
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
        - name: sysbench
          image: portworx/torpedo-sysbench:latest
          env:
            - name: MYSQL_HOST
              value: 127.0.0.1
            - name: MYSQL_ROOT_PASSWORD
              value: password
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-data
