apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-sc-shared
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  priority_io: "high"
  shared: "true"
  io_profile: "cms"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: worpress-sc
provisioner: pxd.portworx.com
parameters:
  repl: "3"
  io_profile: "db"
  priority_io: "high"
allowVolumeExpansion: true