apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-job-config
data:
    fio.job: |
        [global]
        name=fio-rand-RW
        directory=/scratch/
        rw=write
        randrepeat=1
        bs=4K
        direct=1
        do_verify=1
        verify=crc32c
        verify_pattern=0xdeadbeef
        gtod_reduce=1
        disable_lat=0
        gtod_reduce=0
        time_based=1
        runtime=999999999
        [file1]
        size=8G
        ioengine=libaio
        iodepth=128
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fio-ready-probe
data:
  ready-probe.sh: |
    #!/bin/bash
    if [ `cat /root/fio.log | grep 'error\|bad magic header' | wc -l` -ge 1 ]; then 
      exit 1; 
    else 
      exit 0; 
    fi